@startuml EcoCarga-Seq-AltaCargador
title Alta de Cargador (Factory Method + Singleton)
actor Operador
participant ":CargadorService" as S
participant "fabrica:FabricaRapidoDC" as F
participant ":EstacionDeCarga" as E

Operador -> S : altaCargador(tipo="RAPIDO_DC", ubicacion)
S -> F : crearCargador(ubicacion)
F -> F : factoryMethod()
F --> S : cargador:CargadorRapidoDC
S -> E : getInstancia()
E --> S : instancia
S -> E : agregarCargador(cargador)
E --> S : ok
S --> Operador : cargador creado
@enduml
