@startuml VentaSimple-Seq-Configuracion
title Cambiar Formato de Moneda (Observer)
actor Vendedor
participant "config:ConfiguracionI18N" as Cfg
participant "moneda:FormatoMoneda" as FM
participant "fecha:FormatoFecha" as FF

Vendedor -> Cfg : setConfiguracion("ARS", "dd/MM/yyyy")
Cfg -> Cfg : notificar()
Cfg -> FM : actualizar()
FM -> Cfg : getFormatoMoneda()
Cfg --> FM : "ARS"
Cfg -> FF : actualizar()
FF -> Cfg : getFormatoFecha()
Cfg --> FF : "dd/MM/yyyy"
Cfg --> Vendedor : configuracion aplicada
@enduml
